# Generated by Django 2.1.4 on 2018-12-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='Justin', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('listimage', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('blogimage', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media', width_field='width_field')),
                ('summary', models.CharField(max_length=200)),
                ('created', models.DateField(blank=True, null=True)),
                ('heading1', models.CharField(blank=True, default='Justin', max_length=100)),
                ('pra1', models.TextField(blank=True, default='Justin', max_length=2000)),
                ('heading2', models.CharField(blank=True, default='Justin', max_length=100)),
                ('pra2', models.TextField(blank=True, default='Justin', max_length=2000)),
                ('heading3', models.CharField(blank=True, default='Justin', max_length=100)),
                ('pra3', models.TextField(blank=True, default='Justin', max_length=2000)),
                ('heading4', models.CharField(blank=True, default='Justin', max_length=100)),
                ('pra4', models.TextField(blank=True, default='Justin', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Blog', 'Blog'), ('Daily Life', 'Daily Life'), ('Work', 'Work'), ('Study', 'Study')], default='m', help_text='blog type', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Tag'),
        ),
    ]
